// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RiotManagerDb;

namespace RiotManagerDb.Migrations
{
    [DbContext(typeof(RiotManagerContext))]
    partial class RiotManagerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("RiotManagerDb.Matches", b =>
                {
                    b.Property<string>("matchid")
                        .HasColumnType("TEXT");

                    b.Property<string>("puuid")
                        .HasColumnType("TEXT");

                    b.HasKey("matchid");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("RiotManagerDb.Participant", b =>
                {
                    b.Property<string>("matchid")
                        .HasColumnType("TEXT");

                    b.Property<string>("puuid")
                        .HasColumnType("TEXT");

                    b.Property<int>("assists")
                        .HasColumnType("INTEGER");

                    b.Property<int>("baronKills")
                        .HasColumnType("INTEGER");

                    b.Property<int>("bountyLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("champExperience")
                        .HasColumnType("INTEGER");

                    b.Property<int>("champLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("championId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("championName")
                        .HasColumnType("TEXT");

                    b.Property<int>("championTransform")
                        .HasColumnType("INTEGER");

                    b.Property<int>("consumablesPurchased")
                        .HasColumnType("INTEGER");

                    b.Property<int>("damageDealtToBuildings")
                        .HasColumnType("INTEGER");

                    b.Property<int>("damageDealtToObjectives")
                        .HasColumnType("INTEGER");

                    b.Property<int>("damageDealtToTurrets")
                        .HasColumnType("INTEGER");

                    b.Property<int>("damageSelfMitigated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("deaths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("detectorWardsPlaced")
                        .HasColumnType("INTEGER");

                    b.Property<int>("doubleKills")
                        .HasColumnType("INTEGER");

                    b.Property<int>("dragonKills")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("firstBloodAssist")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("firstBloodKill")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("firstTowerAssist")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("firstTowerKill")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("gameEndedInEarlySurrender")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("gameEndedInSurrender")
                        .HasColumnType("INTEGER");

                    b.Property<int>("goldEarned")
                        .HasColumnType("INTEGER");

                    b.Property<int>("goldSpent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("individualPosition")
                        .HasColumnType("TEXT");

                    b.Property<int>("inhibitorKills")
                        .HasColumnType("INTEGER");

                    b.Property<int>("inhibitorTakedowns")
                        .HasColumnType("INTEGER");

                    b.Property<int>("inhibitorsLost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("item0")
                        .HasColumnType("INTEGER");

                    b.Property<int>("item1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("item2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("item3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("item4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("item5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("item6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("itemsPurchased")
                        .HasColumnType("INTEGER");

                    b.Property<int>("killingSprees")
                        .HasColumnType("INTEGER");

                    b.Property<int>("kills")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lane")
                        .HasColumnType("TEXT");

                    b.Property<int>("largestCriticalStrike")
                        .HasColumnType("INTEGER");

                    b.Property<int>("largestKillingSpree")
                        .HasColumnType("INTEGER");

                    b.Property<int>("largestMultiKill")
                        .HasColumnType("INTEGER");

                    b.Property<int>("longestTimeSpentLiving")
                        .HasColumnType("INTEGER");

                    b.Property<int>("magicDamageDealt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("magicDamageDealtToChampions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("magicDamageTaken")
                        .HasColumnType("INTEGER");

                    b.Property<int>("neutralMinionsKilled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("nexusKills")
                        .HasColumnType("INTEGER");

                    b.Property<int>("nexusLost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("nexusTakedowns")
                        .HasColumnType("INTEGER");

                    b.Property<int>("objectivesStolen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("objectivesStolenAssists")
                        .HasColumnType("INTEGER");

                    b.Property<int>("participantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("pentaKills")
                        .HasColumnType("INTEGER");

                    b.Property<int>("physicalDamageDealt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("physicalDamageDealtToChampions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("physicalDamageTaken")
                        .HasColumnType("INTEGER");

                    b.Property<int>("profileIcon")
                        .HasColumnType("INTEGER");

                    b.Property<int>("quadraKills")
                        .HasColumnType("INTEGER");

                    b.Property<string>("riotIdName")
                        .HasColumnType("TEXT");

                    b.Property<string>("riotIdTagline")
                        .HasColumnType("TEXT");

                    b.Property<string>("role")
                        .HasColumnType("TEXT");

                    b.Property<int>("sightWardsBoughtInGame")
                        .HasColumnType("INTEGER");

                    b.Property<int>("spell1Casts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("spell2Casts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("spell3Casts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("spell4Casts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("summoner1Casts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("summoner1Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("summoner2Casts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("summoner2Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("summonerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("summonerLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("summonerName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("teamEarlySurrendered")
                        .HasColumnType("INTEGER");

                    b.Property<int>("teamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("teamPosition")
                        .HasColumnType("TEXT");

                    b.Property<int>("timeCCingOthers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("timePlayed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("totalDamageDealt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("totalDamageDealtToChampions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("totalDamageShieldedOnTeammates")
                        .HasColumnType("INTEGER");

                    b.Property<int>("totalDamageTaken")
                        .HasColumnType("INTEGER");

                    b.Property<int>("totalHeal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("totalHealsOnTeammates")
                        .HasColumnType("INTEGER");

                    b.Property<int>("totalMinionsKilled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("totalTimeCCDealt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("totalTimeSpentDead")
                        .HasColumnType("INTEGER");

                    b.Property<int>("totalUnitsHealed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("tripleKills")
                        .HasColumnType("INTEGER");

                    b.Property<int>("trueDamageDealt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("trueDamageDealtToChampions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("trueDamageTaken")
                        .HasColumnType("INTEGER");

                    b.Property<int>("turretKills")
                        .HasColumnType("INTEGER");

                    b.Property<int>("turretTakedowns")
                        .HasColumnType("INTEGER");

                    b.Property<int>("turretsLost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("unrealKills")
                        .HasColumnType("INTEGER");

                    b.Property<int>("visionScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("visionWardsBoughtInGame")
                        .HasColumnType("INTEGER");

                    b.Property<int>("wardsKilled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("wardsPlaced")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("win")
                        .HasColumnType("INTEGER");

                    b.HasKey("matchid", "puuid");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("RiotManagerDb.Summoner", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfileIconId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RevisionDate")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SummonerLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("puuid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Summoners");
                });
#pragma warning restore 612, 618
        }
    }
}
